### ISSUE TITLE
Crosscompiling from Windows to Mac

### ISSUE THREAD

**Issue by kkevinchou** [veandco/go-sdl2#497]
Hello is there any guidance for crosscompiling from Windows to Mac? I get the following error:

```
$ CGO_ENABLED=1 GOOS=darwin CC="gcc" GOARCH=amd64 go build -o output
# runtime/cgo
gcc: error: x86_64: No such file or directory
gcc: error: unrecognized command line option '-arch'; did you mean '-march='?
```

I am using MinGW

**Comment by kkevinchou** [comment]
Thanks for the suggestion, I was hoping for something a little more out-of-the-box but that's a reasonable workaround 👍

**Comment by veeableful** [comment]
Hi @depili, sorry for taking so long to reply! I added a commit that seems to fix the undefined symbol issue. Could you try the `v0.4.x` branch? If it does fix it, I will tag it immediately.

**Comment by depili** [comment]
Seems to have fixed that linking error, now just running into other issues on my osx-crossbuild with (supposedly) the golang builtin time package...
```
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _runtime.walltime_trampoline.abi0 in go.o
  "_getentropy", referenced from:
      _internal/syscall/unix.libc_getentropy_trampoline.abi0 in go.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
But this is probably unrelated to the go-sdl2 in of itself, just some other issue with osxcross and golang.

**Comment by depili** [comment]
Actually, doing a quick test and just trying to compile the example from go-sdl2 readme results in linking errors with _clock_gettime:

```
package main

import "github.com/veandco/go-sdl2/sdl"

func main() {
	if err := sdl.Init(sdl.INIT_EVERYTHING); err != nil {
		panic(err)
	}
	defer sdl.Quit()

	window, err := sdl.CreateWindow("test", sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED,
		800, 600, sdl.WINDOW_SHOWN)
	if err != nil {
		panic(err)
	}
	defer window.Destroy()

	surface, err := window.GetSurface()
	if err != nil {
		panic(err)
	}
	surface.FillRect(nil, 0)

	rect := sdl.Rect{0, 0, 200, 200}
	surface.FillRect(&rect, 0xffff0000)
	window.UpdateSurface()

	running := true
	for running {
		for event := sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
			switch event.(type) {
			case *sdl.QuitEvent:
				println("Quit")
				running = false
				break
			}
		}
	}
}
```

```
CGO_ENABLED=1 CC=x86_64-apple-darwin15-clang GOOS=darwin GOARCH=amd64 go build -tags static -ldflags "-s -w" foo2.go
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running x86_64-apple-darwin15-clang failed: exit status 1
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _runtime.walltime_trampoline.abi0 in go.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Just compiling a go program printing out time.Now(), runtime.GOOS and runtime.ReadBuildInfo() works when cross-compiled with osxcross.

**Comment by depili** [comment]
Using git head (e59a63461da2cbc20cb0a5bbfc954730e50a5472) of osxcross, if that matters.

**Comment by veeableful** [comment]
Hi @depili, you're right. It seems like macOS SDK 10.11 can't be used, at least with the Go 1.17. I was able to compile with macOS SDK 11.3 but I think any SDK version 10.13 or newer should work which seems to be requirement for Go 1.17 (https://golang.org/doc/go1.17). It might also work with an older Go versions like 1.16 if we don't want to upgrade the macOS SDK. I used this code as a test:
```
package main

/*
#include <stdio.h>

static void foo()
{
        fprintf(stdout, "Hello, World!");
}
*/
import "C"

func main() {
        C.foo()
}
```

**Comment by depili** [comment]
Unfortunately, I can't seem to get osxcross up with 10.13 as
`build_compiler_rt.sh` fails, so can't test. Will try with go 1.16

**Comment by depili** [comment]
Trying with go1.16.9 and SDK 10.11 still runs into a linking problem, just
one this time:

```
***@***.***:~/clock-8001/v4# cat foo.go
package main

import "github.com/veandco/go-sdl2/sdl"

func main() {
	if err := sdl.Init(sdl.INIT_EVERYTHING); err != nil {
		panic(err)
	}
	defer sdl.Quit()

	window, err := sdl.CreateWindow("test",
sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED,
		800, 600, sdl.WINDOW_SHOWN)
	if err != nil {
		panic(err)
	}
	defer window.Destroy()

	surface, err := window.GetSurface()
	if err != nil {
		panic(err)
	}
	surface.FillRect(nil, 0)

	rect := sdl.Rect{0, 0, 200, 200}
	surface.FillRect(&rect, 0xffff0000)
	window.UpdateSurface()

	running := true
	for running {
		for event := sdl.PollEvent(); event != nil; event =
sdl.PollEvent() {
			switch event.(type) {
			case *sdl.QuitEvent:
				println("Quit")
				running = false
				break
			}
		}
	}
}
***@***.***:~/clock-8001/v4# CGO_ENABLED=1
CC=x86_64-apple-darwin15-clang GOOS=darwin GOARCH=amd64 go build -tags
static -ldflags "-s -w" foo.go
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running
x86_64-apple-darwin15-clang failed: exit status 1
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _runtime.walltime_trampoline in go.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
```

Will need to see if I can get any SDK other than 10.11 up with osxcross,
can't go lower than go 1.16 since I use embed that requires go 1.16

**Comment by depili** [comment]
Finally had success, using `liushuyu/osxcross` container that is based on
10.14 SDK and go 1.16. For some reason my attempts of creating the SDK
tarballs via the osxcross/tools/ scripts resulted always in something
non-functional in the end.
