### ISSUE TITLE
Can't build static with Linux / Mac - #if SDL_TTF_VERSION_ATLEAST(2,0,18)

### ISSUE THREAD

**Issue by SolarLune** [veandco/go-sdl2#507]
Hello! I'm trying to build a bit of a complex program of mine ([MasterPlan, a graphical ideaboard](https://github.com/SolarLune/masterplan)) that uses the ttf package, and while it works fine when building the application normally, building statically doesn't work. I'm getting an error, on Manjaro Linux as well as Mac OS:

```
# github.com/veandco/go-sdl2/ttf
../../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.12/ttf/sdl_ttf.go:11:28: error: missing binary operator before token "("
   11 | #if SDL_TTF_VERSION_ATLEAST(2,0,18)
```

Here's the build command I'm using:

```
go build -tags static ./
```

I've been able to build my application statically previously, but just not since updating recently from v0.4.10 to v0.4.12, along with an update in SDL2 version to the latest release (2.0.20), as I recall. Any thoughts? I've installed SDL2 via brew on Mac and from the package manager on Linux, of course, and I'm using go-sdl2 v0.4.12.

**Comment by SolarLune** [comment]
After checking go-sdl2 out and making the following change in ttf/sdl_ttf.go (as I'm using a version of SDL2 that's greater than 2.0.18):

```
/*
#include <stdlib.h>
#include "sdl_ttf_wrapper.h"
void Do_TTF_SetError(const char *str) {
    TTF_SetError("%s", str);
}

static inline void ByteSwappedUNICODE(int swapped)
{
	TTF_ByteSwappedUNICODE(swapped ? SDL_TRUE : SDL_FALSE);
}
*/
```

I now get this when I try to build statically:

```
go build -tags static ./                                                                                                                                  ✔  8s  
# github.com/veandco/go-sdl2/sdl
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_dynapi.c.o): relocation R_X86_64_32 against hidden symbol `SDL_SetError_REAL' can not be used when making a PIE object
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_events.c.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_gesture.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_keyboard.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_mouse.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_quit.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_touch.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_windowevents.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_rwops.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_haptic.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_locale.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_url.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_power.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_render.c.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_yuv_sw.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_render_gles2.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_shaders_gles2.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_render_sw.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_sensor.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_iconv.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_malloc.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_string.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_thread.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_timer.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_bmp.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_clipboard.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_fillrect.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_pixels.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_rect.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_stretch.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_surface.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_video.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_yuv.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(yuv_rgb.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_gamecontroller.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_joystick.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_sysloadso.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_virtualjoystick.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_nullvideo.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_syshaptic.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_threadprio.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_sysjoystick.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_systhread.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_sysmutex.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_syscond.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_systls.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_syssem.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_sysurl.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_syspower.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_syslocale.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_sysfilesystem.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_systimer.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_assert.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_error.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_hints.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_log.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_audio.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_audiocvt.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_audiotypecvt.c.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_mixer.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_wave.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_cpuinfo.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_blendfillrect.c.o): relocation R_X86_64_32S against hidden symbol `SDL_expand_byte' can not be used when making a PIE object
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_blendline.c.o): relocation R_X86_64_32S against hidden symbol `SDL_expand_byte' can not be used when making a PIE object
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_blendpoint.c.o): relocation R_X86_64_32S against hidden symbol `SDL_expand_byte' can not be used when making a PIE object
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_drawline.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_drawpoint.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_RLEaccel.c.o): relocation R_X86_64_32S against hidden symbol `SDL_expand_byte' can not be used when making a PIE object
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_blit.c.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_blit_0.c.o): relocation R_X86_64_32S against hidden symbol `SDL_expand_byte' can not be used when making a PIE object
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_blit_1.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_blit_A.c.o): relocation R_X86_64_32S against hidden symbol `SDL_expand_byte' can not be used when making a PIE object
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_blit_N.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_blit_slow.c.o): relocation R_X86_64_32S against hidden symbol `SDL_expand_byte' can not be used when making a PIE object
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_dummyaudio.c.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_diskaudio.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_nullframebuffer.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_dspaudio.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_dataqueue.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../go-sdl2/sdl/../.go-sdl2-libs/libSDL2_linux_amd64.a(SDL_audiodev.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
```

**Comment by veeableful** [comment]
Hi @SolarLune, thanks for reporting the issue! Unfortunately, I haven't been able to keep the static libraries updated, and that caused the errors above as the SDL2_ttf static library included in the binding is at version 2.0.14 which doesn't recognize SDL_TTF_VERSION_ATLEAST. Nevertheless, I will try my best to update the SDL2_ttf library by tomorrow and inform you here. I apologize for the inconvenience!

**Comment by SolarLune** [comment]
No problem! I wasn't sure if it was just my system updating and incompatibilities arising or what - no worries. I can just build dynamically for now. Thank you very much for the support!

**Comment by veeableful** [comment]
Hi @SolarLune, I managed to compile updated SDL2_ttf libraries albeit they are a lot bigger in size. Would you be able to test them? I have temporarily uploaded the libraries to our object storage bucket [here](https://go-sdl2.veandco.sg-sin1.upcloudobjects.com/.go-sdl2-libs.zip)

You can extract it and then copy the libraries and `include` directory inside over the ones inside `.go-sdl2-libs` in a local copy of `go-sdl2`. Then in your program's `go.mod`, you can a line to have it use the local go-sdl2:
```
replace github.com/veandco/go-sdl2 => [path-to-go-sdl2]
```
If you could confirm that they work, I will commit them to the repository! Hopefully I will find ways to reduce their sizes too.

**Comment by veeableful** [comment]
Please disregard the above. I have made a workaround that is available in `v0.4.14` so you can just static build with the libraries that we have now!

**Comment by SolarLune** [comment]
Hello - sorry for the late reply, but I was able to build my app with go-sdl2 statically since this with one of the latest versions. Thanks a lot for your assistance, @veeableful!
