### ISSUE TITLE
redefinition of enumerator 'SDL_JOYSTICK_POWER_UNKNOWN' errors with top of tree

### ISSUE THREAD

**Issue by mmp** [veandco/go-sdl2#536]
(Many thanks for the go-sdl2 bindings--they're invaluable!)

With top of tree (3624de6c831d) I'm seeing the errors below. From a little investigation, this seems to have been introduced in 28145e5f; if I roll back to 253cca45719b63, it works fine. I think the issue is the `#if !defined(SDL_JoystickPowerLevel)` check there; I don't see anything that would actually `#define` that in the SDL2 code. (Not sure if the check should be `#if !defined(SDL_joystick_h_)`, or if there's something more nuanced there.)

```
# github.com/veandco/go-sdl2/sdl
/Users/mmp/go/pkg/mod/github.com/veandco/go-sdl2@v0.5.0-alpha.3.0.20220906123024-3624de6c831d/sdl/events.go:169:5: error: redefinition of enumerator 'SDL_JOYSTICK_POWER_UNKNOWN'
    SDL_JOYSTICK_POWER_UNKNOWN = -1,
    ^
/opt/homebrew/include/SDL2/SDL_joystick.h:101:5: note: previous definition is here
    SDL_JOYSTICK_POWER_UNKNOWN = -1,
    ^
/Users/mmp/go/pkg/mod/github.com/veandco/go-sdl2@v0.5.0-alpha.3.0.20220906123024-3624de6c831d/sdl/events.go:170:5: error: redefinition of enumerator 'SDL_JOYSTICK_POWER_EMPTY'
    SDL_JOYSTICK_POWER_EMPTY,
    ^
/opt/homebrew/include/SDL2/SDL_joystick.h:102:5: note: previous definition is here
    SDL_JOYSTICK_POWER_EMPTY,   /* <= 5% */
    ^
/Users/mmp/go/pkg/mod/github.com/veandco/go-sdl2@v0.5.0-alpha.3.0.20220906123024-3624de6c831d/sdl/events.go:171:5: error: redefinition of enumerator 'SDL_JOYSTICK_POWER_LOW'
    SDL_JOYSTICK_POWER_LOW,
    ^
/opt/homebrew/include/SDL2/SDL_joystick.h:103:5: note: previous definition is here
    SDL_JOYSTICK_POWER_LOW,     /* <= 20% */
    ^
/Users/mmp/go/pkg/mod/github.com/veandco/go-sdl2@v0.5.0-alpha.3.0.20220906123024-3624de6c831d/sdl/events.go:172:5: error: redefinition of enumerator 'SDL_JOYSTICK_POWER_MEDIUM'
    SDL_JOYSTICK_POWER_MEDIUM,
    ^
/opt/homebrew/include/SDL2/SDL_joystick.h:104:5: note: previous definition is here
    SDL_JOYSTICK_POWER_MEDIUM,  /* <= 70% */
    ^
/Users/mmp/go/pkg/mod/github.com/veandco/go-sdl2@v0.5.0-alpha.3.0.20220906123024-3624de6c831d/sdl/events.go:173:5: error: redefinition of enumerator 'SDL_JOYSTICK_POWER_FULL'
    SDL_JOYSTICK_POWER_FULL,
    ^
/opt/homebrew/include/SDL2/SDL_joystick.h:105:5: note: previous definition is here
    SDL_JOYSTICK_POWER_FULL,    /* <= 100% */
    ^
/Users/mmp/go/pkg/mod/github.com/veandco/go-sdl2@v0.5.0-alpha.3.0.20220906123024-3624de6c831d/sdl/events.go:174:5: error: redefinition of enumerator 'SDL_JOYSTICK_POWER_WIRED'
    SDL_JOYSTICK_POWER_WIRED,
    ^
/opt/homebrew/include/SDL2/SDL_joystick.h:106:5: note: previous definition is here
    SDL_JOYSTICK_POWER_WIRED,
    ^
/Users/mmp/go/pkg/mod/github.com/veandco/go-sdl2@v0.5.0-alpha.3.0.20220906123024-3624de6c831d/sdl/events.go:175:5: error: redefinition of enumerator 'SDL_JOYSTICK_POWER_MAX'
    SDL_JOYSTICK_POWER_MAX
    ^
/opt/homebrew/include/SDL2/SDL_joystick.h:107:5: note: previous definition is here
    SDL_JOYSTICK_POWER_MAX
    ^
/Users/mmp/go/pkg/mod/github.com/veandco/go-sdl2@v0.5.0-alpha.3.0.20220906123024-3624de6c831d/sdl/events.go:176:3: error: typedef redefinition with different types ('enum SDL_JoystickPowerLevel' vs 'enum SDL_JoystickPowerLevel')
} SDL_JoystickPowerLevel;
  ^
/opt/homebrew/include/SDL2/SDL_joystick.h:108:3: note: previous definition is here
} SDL_JoystickPowerLevel;
  ^
8 errors generated.
```

**Comment by veeableful** [comment]
Hi @mmp, thanks for the compliment (it means a lot!) and reporting of this issue. I have implemented a fix for this in the `master` branch.

**Comment by mmp** [comment]
Thanks for the quick fix--confirmed that it works!
