### ISSUE TITLE
examples/audio.go not working with Go 1.5, Windows 8.1

### ISSUE THREAD

**Issue by ArchRobison** [veandco/go-sdl2#153]
I built and ran `examples/audio.go`, but all I hear is a barely perceptible faint click when it starts.  Has anyone else gotten it to work recently?  Any advice on how to debug it?

**Comment by akovaski** [comment]
Yep, I don't hear anything either.

Adding
```go
if err := sdl.Init(sdl.INIT_AUDIO); err != nil {
	log.Println(err)
	return
}
```
to the beginning of main() seems to fix it. Please confirm.

**Comment by ArchRobison** [comment]
There's no `log`:
```
$ go run audio.go
# command-line-arguments
.\audio.go:38: undefined: log in log.Println
```
I tried inserting:
```
if err := sdl.Init(sdl.INIT_AUDIO); err != nil {
    panic(err)
    return
}
```
but I'm still just getting the faint click.

**Comment by akovaski** [comment]
So... did you resolve your problem?

**Comment by ArchRobison** [comment]
Oops.  I accidentally hit the "Close and comment" button instead of "Comment".  

I have not been able to resolve the problem with the `audio.go` example.  However, in my "real" code, the sound is working fine and I'm not sure what I did differently.

**Comment by akovaski** [comment]
ahaha. Well I have made a pull-request #154  that fixes the problem for at-least me. Maybe you could check if that works for you.

**Comment by ArchRobison** [comment]
Yes, that fixed it.  Indeed I wish I had turned down the volume before trying it :-).
